# action.yml
name: 'Build'
description: 'Placeholder for build and test action'
outputs:
  text: # id of output
    description: 'Placeholder input'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "This is a success placeholder"