# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #   TODO RE ADD VERSION AND FIX THIS BS
      - uses: actions/checkout@v2

      - name: Unit test action step
        id: success
        uses: ./.github/actions/unit_tests
        
      - name: Have all tests passed
        run: echo "Tests passed:${{ steps.success.outputs.tests_passed }}"
