# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run dockerfile with python tests
        run: |
<<<<<<< HEAD
          docker build -f Dockerfile_test -t open-audio-controller .
          docker run --env FLASK_APP=open_audio_controller/open_audio_flask.py open-audio-controller
=======
          docker build -f Dockerfile_test -t open-audio-controller . 
	  docker run --env FLASK_APP=open_audio_controller/open_audio_flask.py -it open-audio-controller
>>>>>>> c6b393f1e2303fcb47ccd9dfebb37c1b768f399f
